# Generated by Django 4.1.2 on 2022-10-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodect',
            name='brand',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
