# Generated by Django 4.1.2 on 2022-10-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0002_prodect_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodect',
            name='out_of_stock',
        ),
    ]
