# Generated by Django 4.1.2 on 2022-10-21 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0002_carts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
