# Generated by Django 4.1.2 on 2022-10-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0003_remove_prodect_out_of_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodect',
            new_name='Product',
        ),
    ]
