# Generated by Django 4.1.2 on 2022-10-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0004_rename_prodect_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodect_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='brand', max_length=40),
            preserve_default=False,
        ),
    ]
