# Generated by Django 4.1.2 on 2022-10-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0005_alter_carts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
