# Generated by Django 4.1.2 on 2022-10-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0005_rename_prodect_image_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='out_of_stock',
            field=models.BooleanField(null=True),
        ),
    ]
