# Generated by Django 4.1.2 on 2022-10-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0006_product_out_of_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='out_of_stock',
        ),
    ]
