# Generated by Django 4.1.2 on 2022-10-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0006_alter_carts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_details',
            name='quantity',
        ),
        migrations.AddField(
            model_name='carts',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
