# Generated by Django 4.1.2 on 2022-10-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0007_remove_products_details_quantity_carts_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
