# Generated by Django 4.1.2 on 2022-10-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0009_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(null=True, to='Ecart.carts'),
        ),
    ]
