# Generated by Django 4.1.2 on 2022-10-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0013_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('shipping', 'shipping'), ('delivered', 'delivered')], default='pending', max_length=60),
        ),
    ]
