# Generated by Django 4.1.2 on 2022-10-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0014_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordred_date',
        ),
    ]
