# Generated by Django 4.1.2 on 2022-10-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0016_remove_order_order_items_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(null=True, to='Ecart.carts'),
        ),
    ]
