# Generated by Django 4.1.2 on 2022-10-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0019_remove_order_order_items_order_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='Ecart.carts'),
        ),
    ]
