# Generated by Django 4.1.2 on 2022-10-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0020_alter_order_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='is_active',
            field=models.BooleanField(default='True'),
        ),
    ]
