# Generated by Django 4.1.2 on 2022-10-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0021_carts_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
