# Generated by Django 4.1.2 on 2022-10-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0022_alter_carts_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.IntegerField(null=True),
        ),
    ]
