# Generated by Django 4.1.2 on 2022-10-28 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0024_remove_order_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Wish_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('wished', models.BooleanField(default=True)),
                ('favourite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecart.products_details')),
            ],
        ),
    ]
