# Generated by Django 4.1.2 on 2022-10-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0025_alter_carts_user_wish_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_details',
            name='wished',
            field=models.BooleanField(default=True),
        ),
    ]
