# Generated by Django 4.1.2 on 2022-10-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0026_products_details_wished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_details',
            name='wished',
            field=models.BooleanField(default=False),
        ),
    ]
