# Generated by Django 4.1.2 on 2022-10-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0027_alter_products_details_wished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_details',
            name='wished',
        ),
    ]
