# Generated by Django 4.1.2 on 2022-10-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecart', '0028_remove_products_details_wished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish_list',
            name='favourite',
        ),
        migrations.AddField(
            model_name='wish_list',
            name='favourite',
            field=models.ManyToManyField(null=True, to='Ecart.products_details'),
        ),
    ]
